services:
    files:
        container_name: "rDrama"
        build:
            context: .
        volumes:
            - "./:/rDrama"
            - "./nginx.conf:/etc/nginx/sites-enabled/1"
            - "./nginx-serve-static.conf:/etc/nginx/includes/serve-static"
        links:
            - "redis"
            - "postgres"
        ports:
            - "80:80"
        depends_on:
            - redis
            - postgres

    redis:
        container_name: "redis"
        image: redis
        ports:
            - "6379:6379"

    postgres:
        container_name: "postgres"
        image: postgres
        command: ["postgres", "-c", "log_statement=all"]
        volumes:
            - "./schema.sql:/docker-entrypoint-initdb.d/00-schema.sql"
            - "./seed-db.sql:/docker-entrypoint-initdb.d/10-seed-db.sql"
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
            - "5432:5432"

    opera-proxy:
        container_name: "opera-proxy"
        image: yarmak/opera-proxy
        ports:
            - "18080:18080"
